server:
  port: 8080
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/credit-card
    username: root
    password: sa@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/example/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  jwt:
    secret: mySecretKey

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false