server:
  port: 8080
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:mysql://localhost:3306/credit-card
    username: root
    password: sa@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      routes:
        - id: credit-service
          uri: lb://CREDIT-SERVICE  # Points to the service name registered in Eureka
          predicates:
            - Path=/api/credit/**
  jwt:
    secret: mySecretKey

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false